#!/usr/bin/env bash
set -u

# Constrained GFN2-xTB reoptimization for all TSRE_S substrates (3a-3n)
# using conformers generated by CREST quick GFN-FF searches.
#
# Run from:
# ~/HT_TSs_Opt/Step_1_Templates_Generation/Reisman_JACS_2014
#
# Expected in each substrate folder:
#   crest_conformers.xyz
#   TSRE_S_const.inp
#
# Restart behavior:
#   If reopt/conf_XXXX/xtbopt.xyz already exists, that conformer is skipped.

command -v xtb >/dev/null 2>&1 || {
    echo "ERROR: xtb not found in PATH."
    echo "Activate crest_env first."
    exit 1
}

for d in TSRE_S_3{a..n}_*/
do
    [[ -d "$d" ]] || continue

    echo
    echo "============================================================"
    echo "Substrate: ${d%/}"
    echo "Started:   $(date)"
    echo "============================================================"

    if [[ ! -f "$d/crest_conformers.xyz" ]]; then
        echo "WARNING: $d/crest_conformers.xyz not found. Skipping."
        continue
    fi

    if [[ ! -f "$d/TSRE_S_const.inp" ]]; then
        echo "WARNING: $d/TSRE_S_const.inp not found. Skipping."
        continue
    fi

    rm -rf "$d/conformers"
    mkdir -p "$d/conformers" "$d/reopt"

    awk -v outdir="$d/conformers" '
    BEGIN { n=0; out="" }
    /^[[:space:]]*[0-9]+[[:space:]]*$/ {
        if (out != "") close(out)
        n++
        out=sprintf("%s/conf_%04d.xyz", outdir, n)
    }
    {
        if (out != "") print > out
    }
    ' "$d/crest_conformers.xyz"

    count=$(find "$d/conformers" -maxdepth 1 -type f -name 'conf_*.xyz' | wc -l)
    echo "Conformers found: $count"

    if [[ "$count" -eq 0 ]]; then
        echo "WARNING: no conformers were generated. Skipping."
        continue
    fi

    for xyz in "$d"/conformers/conf_*.xyz
    do
        [[ -f "$xyz" ]] || continue

        name=$(basename "$xyz" .xyz)
        outdir="$d/reopt/$name"

        if [[ -f "$outdir/xtbopt.xyz" ]]; then
            echo "SKIP: $name already completed"
            continue
        fi

        mkdir -p "$outdir"

        cp "$xyz" "$outdir/input.xyz"
        cp "$d/TSRE_S_const.inp" "$outdir/TSRE_S_const.inp"

        (
            cd "$outdir" || exit 1

            xtb input.xyz \
              --gfn 2 \
              --chrg 0 \
              --uhf 1 \
              --input TSRE_S_const.inp \
              --opt \
              > xtb.out 2>&1
        )

        status=$?

        if [[ $status -eq 0 && -f "$outdir/xtbopt.xyz" ]]; then
            echo "DONE: $name"
        else
            echo "WARNING: xTB failed for $name"
            echo "Check: $outdir/xtb.out"
        fi
    done

    done_count=$(find "$d/reopt" -mindepth 2 -maxdepth 2 -type f -name xtbopt.xyz | wc -l)
    echo "Completed xTB optimizations: $done_count / $count"
    echo "Finished: $(date)"
done

echo
echo "============================================================"
echo "All available TSRE_S substrates processed."
echo "Finished: $(date)"
echo "============================================================"
